# Generated by Django 3.0 on 2020-01-14 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=100, unique=True, verbose_name='Имя автора')),
                ('birth_year', models.SmallIntegerField(verbose_name='Дата рождения автора')),
                ('country', models.CharField(max_length=2, verbose_name='Страна автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PubHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование издательства')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, verbose_name='ISBN')),
                ('title', models.TextField(verbose_name='Наименование книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('year_release', models.SmallIntegerField(verbose_name='Год издания')),
                ('copy_count', models.IntegerField(default=1, verbose_name='Количество копий')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Author', verbose_name='Автор')),
                ('pubhouse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='book', to='p_library.PubHouse', verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
